version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: FastAPI/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./FastAPI:/app
    restart: always
    networks:
      - app
    container_name: FastAPI


  streamlit:
    build:
      context: .
      dockerfile: Streamlit/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - ./Streamlit:/app
    environment:
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=2048
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 2g
    restart: always
    networks:
      - app
    container_name: Streamlit

networks:
  app:
    driver: bridge